import Screen

SQUARE_GRID_ROWS = 25
SQUARE_GRID_COLS = 50
LENGTH = 20

WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 500
GRASS_HEIGHT = 40
GRASS_WIDTH = 60
SOLDIER_HEIGHT = 80
SOLDIER_WIDTH = 40
MINE_HEIGHT = 20
MINE_WIDTH = 60
FLAG_HEIGHT = 60
FLAG_WIDTH = 80
BACKGROUND_COLOR = (74, 125, 60)

RUNNING_STATE = 1
LOSE_STATE = 2
WIN_STATE = 3

SOLDIER_IMAGE = "soldier.png"
GRASS_IMAGE = "grass.png"
FLAG_IMAGE = "flag.png"
MINE_IMAGE = "mine.png"
GREEN_GRID = (40, 95, 8)
BLACK_SCREEN = (2, 3, 1)

LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)
LOSE_COLOR = (10, 11, 10)
LOSE_LOCATION =  (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))
LOSE_MESSAGE = "You Lost!"
FONT_NAME = "Calibri"
WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = (89, 89, 89)
WIN_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))
